FROM debian:bookworm-slim
WORKDIR /app
COPY target/gestion /app/gestion
RUN chmod +x /app/gestion
ENV SERVER_PORT=${PORT:-8080}
ENV TZ=Europe/Madrid
RUN useradd -m springuser
USER springuser
ENTRYPOINT ["/app/gestion"]
