CREATE TABLE IF NOT EXISTS centros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS cargos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS miembros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_razon_social VARCHAR(255) NOT NULL,
    centro_id BIGINT,
    telefono VARCHAR(50),
    correo VARCHAR(100),
    cargo_id BIGINT,
    fecha_cargo DATE,
    enlace_whatsapp VARCHAR(255),
    nif_cif VARCHAR(50),
    nacionalidad VARCHAR(100),
    domicilio VARCHAR(255),
    fecha_nacimiento DATE,
    fecha_alta DATE,
    observaciones TEXT,
    fecha_baja DATE
);

CREATE TABLE IF NOT EXISTS historial_cargos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    miembro_id BIGINT NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE,
    cargo_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS news (
    title VARCHAR(255) PRIMARY KEY,
    content TEXT,
    created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    can_manage_permissions BOOLEAN DEFAULT FALSE,
    can_manage_organization BOOLEAN DEFAULT FALSE,
    can_manage_web BOOLEAN DEFAULT FALSE,
    can_manage_finances BOOLEAN DEFAULT FALSE
);
